# Generated by Django 4.2 on 2024-04-05 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSX', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='subject_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
