# Generated by Django 4.2 on 2024-04-05 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSX', '0002_alter_manage_subject_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage',
            name='subject_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
